name: "\U0001F41B Сообщение об ошибке"
description: Сообщите об ошибке, чтобы улучшить работу GigaChain. Для обратной связи о проблемах с безопасностью воспользуйтесь отдельной формой ниже.
labels: ["02 Сообщение об ошибке"]
body:
  - type: markdown
    attributes:
      value: >
        Перед тем как сообщить об ошибке, пожалуйста, убедитесь, что вашей проблемы нет среди открытых issue.
- type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Воспроизведение ошибки
      description: |
        Предоставьте [образец кода](https://stackoverflow.com/help/minimal-reproducible-example), при выполнении которого возникает ошибка. Подойдет как ссылка на Colab, так и отдельный фрагмент кода.
        По возможности, приложите другие примеры кода, сообщения об ошибках и стек трейсы, которые помогут воспроизвести проблему.
        Обратите внимание на корректное [выделение блоков кода с помощью тегов](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting).
        Не нужно присылать скриншоты кода. Такие примеры неудобно читать и их нельзя скопировать.

      placeholder: |
        Опишите шаги для воспроизведения ошибки:

          1.
          2.
          3.
    validations:
      required: true