name: "\U0001F41B Сообщение об ошибке"
description: Сообщите об ошибке, чтобы улучшить работу GigaChain. Для обратной связи о проблемах с безопасностью воспользуйтесь отдельной формой ниже.
labels: ["02 Сообщение об ошибке"]
body:
  - type: markdown
    attributes:
      value: >
        Перед тем как сообщить об ошибке, пожалуйста, убедитесь, что вашей проблемы нет среди открытых issue.
        Затем подробно опишите суть проблему и информацию о том, в каком окружении и с какими версиями библиотек возникает ошибка.
  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Описание ошибки
      description: |
        Напишите короткое описание того, что вы делаете, какое поведение наблюдаете и какого поведения ожидали.
        Пожалуйста приложите код, выполнение которого вызывает ошибку
      placeholder: |
        * Я пытаюсь использовать `gigachain` чтобы сделать X.
        * Я ожидаю получить Y.
        * Вместо этого происходит Z.
  - type: textarea
    id: enviroment
    validations:
      required: true
    attributes:
      label: Окружение и версии библиотек
      description: |
        Пожалуйста приложите информацию об окружении и установленных библиотеках.
        Для этого установите gigachain-cli с помощью команды `pip install gigachain-cli` 
        и выполните команду `gigachain info`.
      placeholder: |
        System Information
        ------------------
        > OS:  Darwin
        > OS Version:  Darwin Kernel Version 23.5.0: Wed May  1 20:09:52 PDT 2024; root:xnu-10063.121.3~5/RELEASE_X86_64
        > Python Version:  3.9.19 (main, Mar 19 2024, 16:08:27) 
        [Clang 15.0.0 (clang-1500.3.9.4)]

        Package Information
        -------------------
        > langchain_core: Installed. No version info available.
        > langchain_community: Installed. No version info available.
        > langsmith: 0.1.84
        > langchain_cli: Installed. No version info available.
        > langchain_experimental: Installed. No version info available.
        > langchain_text_splitters: Installed. No version info available.
        > langchainhub: 0.1.15
        > langserve: Installed. No version info available.

        Packages not installed (Not Necessarily a Problem)
        --------------------------------------------------
        The following packages were not found:

        > langgraph