name: "\U0001F41B Сообщение об ошибке"
description: Сообщите об ошибке, чтобы улучшить работу GigaChain. Для обратной связи о проблемах с безопасностью воспользуйтесь отдельной формой ниже.
labels: ["02 Сообщение об ошибке"]
body:
  - type: markdown
    attributes:
      value: >
        Перед тем как сообщить об ошибке, пожалуйста, убедитесь, что вашей проблемы нет среди открытых issue.
  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Описание ошибки
      description: |
        Напишите короткое описание того, что вы делаете, какое поведение наблюдаете и какого поведения ожидали.
        Пожалуйста приложите код, выполнение которого вызывает ошибку
      placeholder: |
        * Я пытаюсь использовать `gigachain` чтобы сделать X.
        * Я ожидаю получить Y.
        * Вместо этого происходит Z.